### ISSUE TITLE
Desktop with Broadwell chip

### ISSUE THREAD

**Issue by dziny** [rlerdorf/OCSanity#19]
I wonder why there is no config check that would match iMac 16,1 (I know quite rare). I happen to have a mini-PC (NUC style) with iGPU and 5250U processor which I use as TV computer as it quite well matches iMac 16,1 specs. I pick Desktop Haswell when checking my OC plist but it complains at few places. Nevertheless, it is a valid possible Hackintosh configuration.

**Comment by khronokernel** [comment]
So the sanity checker in a sense is a direct copy of the [Install Guide](https://dortania.github.io/OpenCore-Install-Guide/) to a fault, and so because of this Sanity Checker was meant more for users who are following the guide than for those who are just checking it over with their own changes. There's a few ways to work around this:

* Make the SMBIOS check a bit more lax on exact model used
* Update Dortania's guides to properly accommodate weirder hardware
  * This would include mobile hardware in "desktop-like" form factors and desktop AIOs

The former imo isn't that great as again it's supposed to be based off the guides and ensure people don't put in typos(ie. iMac16,1 by accident when iMac15,1 was desired). However there is still a typo in the sense that we are missing iMac16,2, which is a Broadwell S class series so that will need to be resolved.

I feel the best "solution" would be to have proper documentation on tis subject and have it adapted into this project afterwards, so I've opened an issue in Dortania's Bug Tracker:

* https://github.com/dortania/bugtracker/issues/85

I'll try to get around to this sometime this month however Big Sur's release is imminent so unfortunately may be pushed back further as other things become priorities.
